### ISSUE TITLE
Interesting (poor) dask behavior in 

### ISSUE THREAD

**Issue by jhamman** [NCAR/cesm-lens-aws#28] opened 2019-12-08 20:47 UTC
I'm noticing some odd behavior in the example notebook with regard to dask and some transpose logic. I'm not 100% sure this was here before the move to intake-esm so I'm wondering if we're combining datasets in a sub-optimal way. The offending cell is below. I'm about to give a tutorial so I can't dig deeper right now but I'm putting this up so we can come back to it.

```python
winter_seasons = seasons.sel(
    time=seasons.time.where(seasons.time.dt.month == 12, drop=True)
)
winter_trends = linear_trend(
    winter_seasons.chunk({"lat": 20, "lon": 20, "time": -1})
).load() * len(winter_seasons.time)

# Compute ensemble mean from the first 30 members
winter_trends_mean = winter_trends.isel(member_id=range(30)).mean(dim="member_id")
winter_trends_mean
```

![image](https://user-images.githubusercontent.com/2443309/70395905-7ffa2c00-19b8-11ea-9501-0350081dbedd.png)

**Comment by andersy005** [comment] 2019-12-10 20:59
> I'm not 100% sure this was here before the move to intake-esm so I'm wondering if we're combining datasets in a sub-optimal way.

In this particular case, we are not merging/concatenating the zarr stores. Each zarr store ends up in its own xarray dataset:

![Screen Shot 2019-12-10 at 1 49 09 PM](https://user-images.githubusercontent.com/13301940/70567894-0434e680-1b54-11ea-85d2-ec7b506e86f0.png)


After further investigations, I can confirm that intake-esm **is not** the culprit here. I am able to reproduce this behavior without **intake-esm**. 


```python
import fsspec
import xarray as xr

options = dict(anon=True)

ds_20C = xr.open_zarr(fsspec.get_mapper('s3://ncar-cesm-lens/atm/daily/cesmLE-20C-TREFHT.zarr', **options), consolidated=True)
ds_RCP85 = xr.open_zarr(fsspec.get_mapper('s3://ncar-cesm-lens/atm/daily/cesmLE-RCP85-TREFHT.zarr', **options), consolidated=True)
```


![Screen Shot 2019-12-10 at 1 38 34 PM](https://user-images.githubusercontent.com/13301940/70567473-44479980-1b53-11ea-809c-30082c26a6d3.png)

**Dependency versions**

```
numpy      1.17.3
fsspec     0.6.1
xarray     0.14.1
intake     0.5.3
intake_esm 2019.10.15.post92
dask       2.9.0
```
Here's the [notebook ](https://gist.github.com/andersy005/1339f3ad6be86b72000724819d96f69a#file-cesm-lens-aws-poor-dask-behavior-ipynb) used to reproduce this behavior.

Unfortunately, I can't really tell whether this behavior has always been there and/or it is caused by recent changes in dask/xarray.

**Comment by jeffdlb** [comment] 2019-12-10 22:00
I believe each chunk (at least for TREFHT) contains the entire 288x192 lat/lon range, so does this line mean each chunk ends up getting read (288/20)*(192/20)=150 times, or even 20x20=400 times?

winter_trends = linear_trend(
    winter_seasons.chunk({"lat": 20, "lon": 20, "time": -1})
).load() * len(winter_seasons.time)

**Comment by andersy005** [comment] 2020-08-24 22:54
Closing this issue for the time being...My current speculation is that it has to do with xarray's `apply_ufunc`, but  I was unable to determine the exact root cause. I may re-open it in the future :)

**Closed by andersy005** 2020-08-24 22:54 UTC

**Comment by dcherian** [comment] 2020-08-24 23:08
Could use `da.polyfit` now and see if the same behaviour persists.

**Comment by andersy005** [comment] 2020-08-25 00:08
> Could use da.polyfit now and see if the same behaviour persists.

👍 I had forgotten about `da.polyfit`. I will look into it tomorrow.
